image: Visual Studio 2015

environment:
  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\ci\\run_with_env.cmd"
    PYTHON: "C:\\Python36"
    PYTHON_SUFFIX: ""

  matrix:
#    -  TARGET_PYTHON: "C:\\Python35"
#       PYQT5_VERSION: 5.6
#       QT_BASE_PATH: c:\\Qt\\5.6

    -  TARGET_PYTHON: "C:\\Python36"
       PYQT5_VERSION: 5.8.2
       QT_BASE_PATH: c:\\Qt\\5.8

    -  TARGET_PYTHON: "C:\\Python36-x64"
       PYTHON_SUFFIX: "-x64"
       PYQT5_VERSION: 5.8.2
       QT_BASE_PATH: c:\\Qt\\5.8

    -  TARGET_PYTHON: "C:\\Python36"
       PYQT5_VERSION: 5.7.1
       QT_BASE_PATH: c:\\Qt\\5.7

    -  TARGET_PYTHON: "C:\\Python36-x64"
       PYTHON_SUFFIX: "-x64"
       PYQT5_VERSION: 5.7.1
       QT_BASE_PATH: c:\\Qt\\5.7

    -  TARGET_PYTHON: "C:\\Python35"
       PYQT5_VERSION: 5.9
       QT_BASE_PATH: c:\\Qt\\5.9

    -  TARGET_PYTHON: "C:\\Python35-x64"
       PYTHON_SUFFIX: "-x64"
       PYQT5_VERSION: 5.9
       QT_BASE_PATH: c:\\Qt\\5.9

    -  TARGET_PYTHON: "C:\\Python35"
       PYQT5_VERSION: 5.8.2
       QT_BASE_PATH: c:\\Qt\\5.8

    -  TARGET_PYTHON: "C:\\Python35-x64"
       PYTHON_SUFFIX: "-x64"
       PYQT5_VERSION: 5.8.2
       QT_BASE_PATH: c:\\Qt\\5.8

    -  TARGET_PYTHON: "C:\\Python35"
       PYQT5_VERSION: 5.7.1
       QT_BASE_PATH: c:\\Qt\\5.7

    -  TARGET_PYTHON: "C:\\Python35-x64"
       PYTHON_SUFFIX: "-x64"
       PYQT5_VERSION: 5.7.1
       QT_BASE_PATH: c:\\Qt\\5.7

#    -  TARGET_PYTHON: "C:\\Python35-x64"
#       PYTHON_SUFFIX: "-x64"
#       PYQT5_VERSION: 5.6
#       QT_BASE_PATH: c:\\Qt\\5.6

    -  TARGET_PYTHON: "C:\\Python34"
       PYQT5_VERSION: 5.5.1
       QT_BASE_PATH: c:\\Qt\\5.5

    -  TARGET_PYTHON: "C:\\Python34-x64"
       PYTHON_SUFFIX: "-x64"
       PYQT5_VERSION: 5.5.1
       QT_BASE_PATH: c:\\Qt\\5.5

    -  TARGET_PYTHON: "C:\\Python36"
       PYQT5_VERSION: 5.11.2
       QT_BASE_PATH: c:\\Qt\\5.11

    -  TARGET_PYTHON: "C:\\Python36-x64"
       PYTHON_SUFFIX: "-x64"
       PYQT5_VERSION: 5.11.2
       QT_BASE_PATH: c:\\Qt\\5.11

    -  TARGET_PYTHON: "C:\\Python36"
       PYQT5_VERSION: 5.10.1
       QT_BASE_PATH: c:\\Qt\\5.10

    -  TARGET_PYTHON: "C:\\Python36-x64"
       PYTHON_SUFFIX: "-x64"
       PYQT5_VERSION: 5.10.1
       QT_BASE_PATH: c:\\Qt\\5.10

    -  TARGET_PYTHON: "C:\\Python36"
       PYQT5_VERSION: 5.9.2
       QT_BASE_PATH: c:\\Qt\\5.9

    -  TARGET_PYTHON: "C:\\Python36-x64"
       PYTHON_SUFFIX: "-x64"
       PYQT5_VERSION: 5.9.2
       QT_BASE_PATH: c:\\Qt\\5.9

# https://www.appveyor.com/docs/how-to/rdp-to-build-worker/
init:
  - ps: if (Get-ChildItem Env:ENABLE_RDP -ErrorAction SilentlyContinue) {iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))} else {echo RDP not enabled}

build_script:
  - "%PYTHON%%PYTHON_SUFFIX%\\python venv.py"
  - copy "%PYTHON%%PYTHON_SUFFIX%\\python3.dll" "venv\\Scripts"
  - "venv\\Scripts\\python -m pip freeze"
  # Build the compiled extension
  - "%TARGET_PYTHON%\\python stderr.py"
  - "%TARGET_PYTHON%\\python -m virtualenv target_venv"
  - if exist "%TARGET_PYTHON%\\python3.dll" (copy "%TARGET_PYTHON%\\python3.dll" "target_venv\\Scripts") else (copy "%TARGET_PYTHON%\\DLLs\\python3.dll" "target_venv\\Scripts")
  - "target_venv\\Scripts\\pip install requests==2.13.0"
  - "target_venv\\Scripts\\pip install vcversioner==2.16.0.0"
  - "target_venv\\Scripts\\pip install wheel==0.30.0a0"
  - "target_venv\\Scripts\\python -m pip freeze"
  - "target_venv\\Scripts\\python setup.py bdist_wheel"
  - "copy dist\\*.whl ."

artifacts:
  - path: '*.whl'

# https://www.appveyor.com/docs/how-to/rdp-to-build-worker/
on_finish:
  - ps: if (Get-ChildItem Env:ENABLE_RDP -ErrorAction SilentlyContinue) {$blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))} else {echo RDP not enabled}
